### ISSUE TITLE
Downgrading from DSM7.2 to DSM6.24 is not supported！

### ISSUE THREAD

**Issue by uranus829** [007revad/Synology_HDD_db#117]
The system has detected that one or more hard disks are not supported by the current DSM version, it is recommended to reinsert the hard disks into the original device to continue using.

The following is the record of executing the script.
----------------------------------------------------------------------------------
root@Brong:~# ./syno_hdd_db.sh -nrf --showedits
Synology_HDD_db v3.0.56
DS916+-j DSM 6.2.4-25556-7 

Using model: ds916+
Using options: -nrf --showedits

HDD/SSD models found: 1
WD80EFZX-68UW8N0,83.H0A83

No M.2 drives found

No M.2 PCIe cards found

No Expansion Units found

WD80EFZX-68UW8N0 already exists in ds916+_host_v7.db
WD80EFZX-68UW8N0 already exists in ds916+_host_v7.db.new

Support disk compatibility already disabled.

Disabled drive db auto updates.

    "WD80EFZX-68UW8N0": {
      "83.H0A83": {
        "compatibility_interval": [
          {
            "compatibility": "support",
            "not_yet_rolling_status": "support",
            "fw_dsm_update_status_notify": false,
            "barebone_installable": true
          }
        ]
      },
      "default": {

You may need to reboot the Synology to see the changes.

**Comment by 007revad** [comment]
> The system has detected that one or more hard disks are not supported by the current DSM version

That message is not related to unsupported drive models. It would be because DSM 6 does not recognise the partition layout of drives that have been used in DSM 7.

_**I hope you backed up your data before downgrading to DSM 6**_.

DSM 6 does not have an online assemble option in storage manager (like DSM 7 does). So you'd probably need to assemble the storage pool via SSH.

Try to assemble the storage pool with:
`mdadm -AsfR && vgchange -ay`

Then reboot and see if DSM mounts your volume(s).
