### ISSUE TITLE
Storage pool on E10M20-T1 on DS1618+ cannot be created

### ISSUE THREAD

**Issue by Edwardvanderveen** [007revad/Synology_HDD_db#118]
Awsome script. Two remarks:

1) on my DS1618+ i have a E10M20-T1 card with two samsung 980 pro 2tb nvme. I deleted the cache and ran the script, but synology 7.2-64570 update 1 does not allow me to create a storage pool on the pcie card. Anything I am doing wrong or forgetting?

2) Since the nvme's are getting bigger, is it possible to partition the nvme's and use one partition on both nvme's as cache and the other partitions on both nvme's as storage pool with raid?

Thanks for the work! Edward

**Comment by 007revad** [comment]
The DSM ui won't let you create a storage pool on NVMe drives in PCIe card. But my https://github.com/007revad/Synology_M2_volume script will partition the drive and create the storage pool so you can then do an online assemble and create the volume in storage manager.

I haven't looked at how DSM creates or manages an NVMe cache, but since a couple of people have asked about splitting NVMe drives into cache and storage pool I will eventually have a look at it.

**Comment by Edwardvanderveen** [comment]
Hi, did you ever had the opportunity to look whether the enhancement I proposed for large SSD drives was possible?

Thanks for the great work Edward

**Comment by 007revad** [comment]
Cache drives have 1 single partition that uses the whole drive. Drives with storage pools have some free space, a system partition, a swap partition and a data partition. DSM expects the cache to be partition 1. But on a data drive partition 1 is the ssytem partition. So I don't think it's possible.

> The DSM ui won't let you create a storage pool on NVMe drives in PCIe card.

FYI, this script, since v3.3.70, now enables creating storage pools in Storage Manager for M.2 drives in PCIe adaptor cards (for DSM 7.2.1 and above only). So there's no need for the syno_m2_volume script.
