### ISSUE TITLE
Suggestion: Set Writemostly for DSM and Swap to HDD if have SSD

### ISSUE THREAD

**Issue by Xeroxxx** [007revad/Synology_HDD_db#318]
I found out if you have an hybrid environement and a SSD is part of you NAS between all those HDDs you can configure mdadm to primary read Swap and DSM from your SDD instead of the HDDs to gain access times.

Did a write-up over here: https://www.techspark.de/speed-up-synology-dsm-with-hdd-ssd/

I think that would be a great addition to your script.

Cheers

**Comment by 007revad** [comment]
Interesting. I wanted more information on this so after reading your write-up I found https://raid.wiki.kernel.org/index.php/Write-mostly.

I'll have to install another drive in my Synology to test this (because md0 and md1 are not mirrored to my NVMe drives or HDD in an expansion unit).

I might start with a separate script. It would have to also cater for newer models that use device tree and use `/sys/block/md0/md/dev-sata1p1` or `/sys/block/md0/md/dev-sas1p1`. People would need to specify their fast drive (or drives) because the script would have no easy way to determine which drive or drives are faster. Though the script could just set all internal HDDs as writemostly if there is an innternal SSD found.

Currently mine show `in_sync`
```
# cat /sys/block/md0/md/dev-sata3p1/state
in_sync
```
It looks like the script would need to `echo writemostly > ...` after each boot.

**Comment by Xeroxxx** [comment]
I've to check what happens after a restart. You can specific the parameter on volume creation as well, but this is actually risky and not a path I would follow.

**Comment by Xeroxxx** [comment]
@007revad I confirm writemostly stays intact after a restart.

**Comment by 007revad** [comment]
@Xeroxxx 

Do you want to set your drives back in_sync then try this script: https://github.com/007revad/Synology_HDD_db/blob/test/writemostly_test.sh

It checks that there are SSD and HDD drives and if there both it sets writemostly for the HDDs.

If it works I'll add the code to syno_hdd_db

**Comment by Xeroxxx** [comment]
Currently extending my storage pool with an additional drive. Will do afterwards! (ETA 2 days)

**Comment by Xeroxxx** [comment]
It does work and sets the variable on all HDDs in my case. I can do a pull request for unset, but I'm not sure how you want this to be implemented. 

`1 internal SSD
5 internal HDD

md0 sda: in_sync,write_mostly
md1 sda: in_sync,write_mostly

md0 sdb: in_sync,write_mostly
md1 sdb: in_sync,write_mostly

md0 sdc: in_sync,write_mostly
md1 sdc: in_sync,write_mostly

md0 sdd: in_sync,write_mostly
md1 sdd: in_sync,write_mostly

md0 sde: in_sync,write_mostly
md1 sde: in_sync,write_mostly`

**Comment by 007revad** [comment]
> but I'm not sure how you want this to be implemented.

I chose to make it automatically set writemostly one HDDs because it was easier to do. The other alternatives are: 
1. Test the speed of each internal drive and pick the fastest one (complicated but possible).
2. Let the user specify the fast drive, or drives, as part of the option. Like --sdd=sda,sdb

I'm not sure yet either. I've been trying to think of what letter to use for the optional flag that relates to what it does. These are already used:
```
  -s, --showedits       Show edits made to <model>_host db and db.new file(s)
  -n, --noupdate        Prevent DSM updating the compatible drive databases
  -r, --ram             Disable memory compatibility checking (DSM 7.x only)
  -f, --force           Force DSM to not check drive compatibility
  -i, --incompatible    Change incompatible drives to supported
  -w, --wdda            Disable WD Device Analytics to prevent DSM showing
  -p, --pcie            Enable creating volumes on M2 in unknown PCIe adaptor
  -e, --email           Disable colored text in output scheduler emails
      --restore         Undo all changes made by the script
      --autoupdate=AGE  Auto update script (useful when script is scheduled)
  -h, --help            Show this help message
  -v, --version         Show the script version
```

**Comment by Xeroxxx** [comment]
I'm sorry I completely misunderstood. I thought you want me to toggle my active writemostly back.

It works completely fine, I thought the script should set it back to in_sync and echo -writemostly when its triggered again or with a switch.

You implementation is fine, no need for option 1 or 2.

**Comment by 007revad** [comment]
I've released a new version with the writemostly option. 
https://github.com/007revad/Synology_HDD_db/releases/tag/v3.5.96 
```
  -S, --ssd=DRIVE       Enable write_mostly on slow internal drives so DSM 
                        runs from the fast internal drive(s).
                          -S automatically sets internal SSDs as DSM preferred
                          --ssd=DRIVE requires the fast drive(s) as argument,
                          or restore as the argument to reset drives to default
                          --ssd=sata1 or --ssd=sata1,sata2 or --ssd=sda etc
                          --ssd=restore
```

**Comment by Xeroxxx** [comment]
Maybe replace "runs" to "primary reads" from SSDs or individual configured drives. But only a suggestion. I can do a PR/MR if you like.

Thanks for your work, think that helps others alot!

**Comment by 007revad** [comment]
You can make a PR/Mr

It has to be 80 chars or less. I don't know why I put a full stop on the end.

You could change it to something like the following:
```
  -S, --ssd=DRIVE       Enable write_mostly on slow internal drives so DSM 
                        primary reads are from internal SSDs or your selected
                        fast internal HDDs
```

**Comment by Xeroxxx** [comment]
I did a proposal. Feel free to edit. However please feel free to edit.

**Comment by Xeroxxx** [comment]
@007revad Just to document that. The setting survives updates.
