### ISSUE TITLE
The script doesnt run

### ISSUE THREAD

**Issue by SayonaRRRa** [007revad/Synology_HDD_db#32]
Runing this on Xpenology redpill loader
920+ DSM 7.1.1-42962 Update 4
I am new to this and would like to run this script. I know nothing about how to run the script.
I putty into the machine like you would.
I did run however a python one and it worked but this shows up as:
```

root@NAS-SLIM:~# cd /tmp
root@NAS-SLIM:/tmp# sudo script.sh
sudo: script.sh: command not found

```

**Comment by 007revad** [comment]
Because the script is not in a location that is in DSM's path variable `/sbin, /bin, /usr/sbin, /usr/bin, /usr/syno/sbin, /usr/syno/bin, /usr/local/sbin, /usr/local/bin` you need to type the path to where the script is located.

For example, if you saved the script to your home folder on volume 1 and your username was bob you'd type:

`sudo /volume1/homes/bob/script.sh`
