### ISSUE TITLE
Failed to load attribute DB

### ISSUE THREAD

**Issue by IngmarStein** [007revad/Synology_HDD_db#348]
I see a lot of messages like the following in `/var/log/messages`:

```
DS923 synostgd-disk[9493]: smartctl/smartctl_nvme_smart_info_get.c:232 Failed to load attribute DB of disk /dev/nvme0n1
```

Is this just an expected outcome after using this tool? It seems harmless - I don't see any broken functionality in Storage Manager, fwiw.

**Comment by 007revad** [comment]
I'd like to know if people get those spammy log entries before running syno_hdd_db.

For each NVMe drive I'm getting multiple of these at 18:43 each day:
```
DISKSTATION synowebapi_SYNO.Storage.CGI.Smart_1_get_health_info[21402]: smartctl/smartctl_nvme_smart_info_get.c:232 Failed to load attribute DB of disk /dev/nvme0n1
```
And multiple of these at midnight each day:
```
DISKSTATION syno_disk_data_collector[19829]: smartctl/smartctl_nvme_smart_info_get.c:232 Failed to load attribute DB of disk /dev/nvme0n1
```
They seem to be harmless, but add a spam to the log.

I wonder if it's because the drives are not on the smartmontools db files:
```
/var/lib/smartmontools/drivedb.db
/var/lib/smartmontools/synodrivedb.db
````
