### ISSUE TITLE
Nvme detected but no disk

### ISSUE THREAD

**Issue by Lesiu76** [007revad/Synology_HDD_db#56]
Hi,

I don't know what i'm doing wrong. 
after running script my nvme installed on pci card is detected and added to compatibility list. However disk is not shown in dsm 7 under hdd/ssd and can't create pool or cache.
Can it be that i'm using some simple pci converter to nvme ? Not approved by Synology.

RS1221+
DSM 7.1.1 u4
Script - latest
M2 drive ssd 960 pro samsung

Also when running script: i have error on line 500 /run/synostorage/disk/$(basename -- "$d")/m2_pool_support: No such file or directory

Script also reporting: 
No M.2 cards found
No Expansion Units found

**Comment by 007revad** [comment]
That error is interesting because to get that far your Synology must have a /sys/block/nvme device but no /run/synostorage/disks/nvme active disk.

I would assume it is definitely because the PCIe card is not a Synology PCIe card. I do have another script that _**may**_ trick DSM into thinking your PCIe card is a Synology card. https://github.com/007revad/Synology_enable_M2_volume

**Comment by 007revad** [comment]
OP not responding
