### ISSUE TITLE
ERROR Memory size is not numeric: 'No'

### ISSUE THREAD

**Issue by phillipmcmahon** [007revad/Synology_HDD_db#93]
Running the latest script with -nr flags. I get the following output error

<img width="587" alt="Screenshot 2023-06-21 at 13 45 26" src="https://github.com/007revad/Synology_HDD_db/assets/1891527/95123807-de0f-42e9-9d07-660927fbeab7">

`$ sudo dmidecode -t memory | grep "[Ss]ize"
	Size: 8192 MB
	Size: No Module Installed
	Size: 16384 MB
	Size: No Module Installed`

Huge thanks for this script btw, it's an essential!

**Comment by 007revad** [comment]
Thank you. I also noticed the script didn't show the current max memory setting.

```
$ sudo dmidecode -t memory | grep "[Ss]ize"
 Size: 8192 MB
 Size: No Module Installed
 Size: 16384 MB
 Size: No Module Installed
```
Since DSM 7.2 was released, different Synology models' output different information for dmidecode -t memory. I don't know why, and it's not the actual dmidecode binary that's different. I just ran the DS1621xs+ dmidecode binary on a DS720+ with an empty memory slot and it didn't return "No Module Installed" for the empty slot.

```
# /volume1/scripts/dmidecode_1621xs -t memory | grep "[Ss]ize"
 Size: 2048 MB
```

I've disabled the warning for non-numeric values - as the script skips them anyway, and will show an error if the total memory size is non-numeric.

I've fixed it in https://github.com/007revad/Synology_HDD_db/releases/tag/v3.0.56 or you can run v3.0.55 again and let it update itself to 3.0.56

**Comment by phillipmcmahon** [comment]
Many thanks!

BTW running the script doesn't auto-update. Do I need to specify a specific flag, as I can't see an option...?

**Comment by phillipmcmahon** [comment]
Thanks so much!
